name: sea_level_rise
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.12
  - geopandas=0.9.0
  - matplotlib=3.4.3
  - numpy=1.21.2
  - ipywidgets=7.7.2
  - jupyterlab=3.1.12
